FROM based_golang_consul

ENV HOME_DIR /home/eric

WORKDIR ${HOME_DIR}
COPY ./main.go ${HOME_DIR}
COPY supervisord.conf /etc/supervisord.conf
RUN mkdir -p ${HOME_DIR}/bin \
	&& go build -o ./bin/main main.go
	

CMD ["/usr/bin/supervisord"]

EXPOSE 8080
